name: mycomac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pip=22.0.4
  - ipykernel=6.13.0
  - jupyterlab=3.3.4
  - matplotlib=3.5.1
  - ipympl=0.9.0
  - numpy=1.22.3
  - scipy=1.8.0
  - sympy=1.10.1
  - autopep8=1.6.0
  - pip:
    - sounddevice==0.4.4
    - soundfile==0.10.3.post1
    - sfs==0.6.2
    
